apiVersion: v1
kind: Secret
metadata:
  name: account-secrets
  namespace: account
type: Opaque
stringData:
  POSTGRES_URI: postgres://account:account@postgres.account.svc.cluster.local:5432/account?sslmode=disable
