apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-account.yaml
  - account-secret.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - migrations-configmap.yaml
  - account-app.yaml
  - account-hpa.yaml
