apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cadvisor.yaml
  - prometheus-rbac.yaml
  - otel-collector-configmap.yaml
  - otel-collector.yaml
  - jaeger.yaml
  - prometheus-configmap.yaml
  - prometheus.yaml
  - grafana-configmaps.yaml
  - grafana.yaml
